### ISSUE TITLE
/nudes

### ISSUE THREAD

**Issue by lpwisniewski** [Anastadev/anastasia#7]
There is not enough women in Ensimag, we need to see some nudes.

**Comment by metaheavens** [comment]
We need to see*

**Comment by Pirkoa** [comment]
Correct english please

**Comment by metaheavens** [comment]
Sorry, autocorrect. There is note enought women in Ensimag, we need to see some nudes.

**Comment by Pirkoa** [comment]
@metaheavens PLZ RLLY LEARN HOW TO SPEAK FFS

**Comment by metaheavens** [comment]
Sorry, auto correct. There is not enought women in Ensimag, we need to see some nudes.

**Comment by metaheavens** [comment]
@Pirkoa Sorry, autocorrect. There is notre enough women in Ensimag, we to see some nudes.
